version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - unconvert
    - unused
    - asciicheck
    - errorlint
    - depguard
    - goconst
    - makezero
    - nonamedreturns
    - predeclared
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/aws/aws-sdk-go/aws
              desc: 'use v2 sdk instead'
    gocritic:
      disabled-checks:
        - newDeref # it's wrong on generics
    govet:
      enable:
        - shadow
  exclusions:
    rules:
      - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*\\.Exit|.*Flush|os\\.Remove(All)?|.*printf?|fmt\\.Fprintln|os\\.(Un)?Setenv|io\\.WriteString|io\\.Copy). is not checked"
        linters:
          - errcheck
      - text: 'declaration of "err"'
        linters:
          - govet
      # it's all fake
      - text: "G101" # G101: potential hard coded creds
        linters:
          - gosec
      # yea, it's a test proxy. we're way beyond security
      - text: "G402" # TLS InsecureSkipVerify set true
        linters:
          - gosec
      # it's used for a serial number
      - text: "G404" # G404: Use of weak random number generator (math/rand instead of crypto/rand)
        linters:
          - gosec
      - text: "QF1001"
        linters:
          - staticcheck
      - text: "QF1003"
        linters:
          - staticcheck
    paths:
      - scripts

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true
